name: vortex_launcher
description: A Flutter app mimicking the iOS home screen with a custom app store.

environment:
  sdk: '>=2.12.0 <3.0.0'  # Adjust the SDK constraint to match your setup

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  webview_flutter: ^4.0.7
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  flutter_inappwebview: ^5.3.2
  shared_preferences: ^2.0.8
  file_picker: ^4.1.6
  image_picker: ^0.8.4+4
  audioplayers: ^0.20.1
  camera: ^0.11.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/backgrounds/
    - assets/lockscreen_background.png
